[package]
  cjc-version = "1.0.0"
  name = "realworld_backend_cangjie_cjoy"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  src-dir = ""
  output-type = "executable"
  compile-option = "-lcrypt32"
  override-compile-option = ""
  link-option = ""
  [package.package-configuration."cjoy.examples.chuncked"]
    output-type = "static"
  [package.package-configuration."cjoy.examples.fileserver"]
    output-type = "static"
  [package.package-configuration."cjoy.examples.macros"]
    output-type = "static"
  [package.package-configuration."cjoy.examples.mcpclient"]
    output-type = "static"
  [package.package-configuration."cjoy.examples.mcpserver"]
    output-type = "static"
  [package.package-configuration."cjoy.examples.multipart"]
    output-type = "static"
  [package.package-configuration."cjoy.examples.rest"]
    output-type = "static"
  [package.package-configuration."cjoy.examples.simple"]
    output-type = "static"
  [package.package-configuration."cjoy.examples.sse"]
    output-type = "static"
  [package.package-configuration."cjoy.examples.tls"]
    output-type = "static"
  [package.package-configuration."cjoy.examples.websocket"]
    output-type = "static"

[dependencies]
  cjoy = { git = "https://gitcode.com/Cangjie-SIG/cjoy.git", branch = "main" }